// Seed generator: parse data/baystate-2026/plan-full.md and emit
// supabase/seed.sql — a full-fidelity, idempotent seed of the 98-day plan.
//
// Run: npm run seed:generate  (tsx scripts/seed/generate-seed.ts)
//
// The output is committed. It uses deterministic UUIDs and upserts, so the
// Conductor can apply it repeatedly via the Supabase MCP without duplicating
// rows or cascade-deleting any user data.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parsePlan } from './parse-plan';
import { uuid5, upsert } from './sql';
import type { ParsedPlan } from './types';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '../..');
const SOURCE = resolve(ROOT, 'data/baystate-2026/plan-full.md');
const OUT = resolve(ROOT, 'supabase/seed.sql');

const SLUG = 'baystate-2026';

const planId = () => uuid5(`plan:${SLUG}`);
const phaseId = (i: number) => uuid5(`phase:${SLUG}:${i}`);
const weekId = (i: number) => uuid5(`week:${SLUG}:${i}`);
const dayId = (date: string) => uuid5(`day:${SLUG}:${date}`);
const sessionId = (date: string, slot: string) => uuid5(`session:${SLUG}:${date}:${slot}`);
const altId = (date: string, gate: string) => uuid5(`alt:${SLUG}:${date}:${gate}`);
const milestoneId = (i: number) => uuid5(`milestone:${SLUG}:${i}`);
const checkpointId = (i: number) => uuid5(`checkpoint:${SLUG}:${i}`);

/** Map a week index to its owning phase index. */
function phaseIndexForWeek(plan: ParsedPlan, weekIndex: number): number {
  const phase = plan.phases.find((p) => weekIndex >= p.startWeek && weekIndex <= p.endWeek);
  if (!phase) throw new Error(`No phase for week ${weekIndex}`);
  return phase.phaseIndex;
}

function generate(plan: ParsedPlan): string {
  const out: string[] = [];
  out.push('-- =============================================================================');
  out.push('-- supabase/seed.sql — GENERATED by scripts/seed/generate-seed.ts. Do not edit.');
  out.push('-- Full-fidelity seed of the Baystate 2026 half-marathon plan:');
  out.push('--   1 plan, 11 phases, 14 weeks, 98 days, 196 day_sessions,');
  out.push('--   day_alternatives for the symptom-gated days, 9 milestones, 4 checkpoints.');
  out.push('-- Idempotent: deterministic UUIDs + upserts. Safe to re-apply.');
  out.push('-- =============================================================================');
  out.push('');
  out.push('begin;');
  out.push('');

  const pid = planId();
  const m = plan.meta;

  // --- plan ---
  out.push('-- plan');
  out.push(
    upsert('plans', {
      id: pid,
      slug: m.slug,
      title: m.title,
      version: m.version,
      prepared_on: m.preparedOn,
      status: 'active',
      athlete_name: m.athleteName,
      athlete_age: m.athleteAge,
      race_name: m.raceName,
      race_distance_km: m.raceDistanceKm,
      race_date: m.raceDate,
      race_start_time: m.raceStartTime,
      race_location: m.raceLocation,
      race_course_notes: m.raceCourseNotes,
      start_date: m.startDate,
      end_date: m.endDate,
      total_planned_km: m.totalPlannedKm,
      north_star: m.northStar,
      plan_logic: m.planLogic,
      goal_a: m.goalA,
      goal_b: m.goalB,
      goal_c: m.goalC,
    }),
  );
  out.push('');

  // --- private plan notes (owner-only sidecar; sealed decision D1) ---
  // The clinical/injury narrative never lands on the public `plans` table; it
  // goes to the owner-only `plan_private_notes` table. Only emitted when there
  // is something to store. Conflict target is plan_id (the primary key).
  if (m.medicalNotes !== null || m.athleteNotes !== null) {
    out.push('-- private plan notes (owner-only)');
    out.push(
      upsert(
        'plan_private_notes',
        {
          plan_id: pid,
          medical_notes: m.medicalNotes,
          athlete_notes: m.athleteNotes,
        },
        'plan_id',
      ),
    );
    out.push('');
  }

  // --- phases ---
  out.push('-- phases');
  for (const p of plan.phases) {
    out.push(
      upsert('plan_phases', {
        id: phaseId(p.phaseIndex),
        plan_id: pid,
        phase_index: p.phaseIndex,
        name: p.name,
        start_week: p.startWeek,
        end_week: p.endWeek,
        description: null,
      }),
    );
  }
  out.push('');

  // --- weeks ---
  out.push('-- weeks');
  for (const w of plan.weeks) {
    out.push(
      upsert('plan_weeks', {
        id: weekId(w.weekIndex),
        plan_id: pid,
        phase_id: phaseId(phaseIndexForWeek(plan, w.weekIndex)),
        week_index: w.weekIndex,
        start_date: w.startDate,
        end_date: w.endDate,
        phase_label: w.phaseLabel,
        planned_km: w.plannedKm,
        range_min_km: w.rangeMinKm,
        range_max_km: w.rangeMaxKm,
        previous_text: w.previousText,
        pct_change_text: w.pctChangeText,
        run_days: w.runDays,
        long_run_km: w.longRunKm,
        coaching_note: w.coachingNote,
        performance_target: w.performanceTarget,
        injury_target: w.injuryTarget,
        bike_note: w.bikeNote,
        strength_note: w.strengthNote,
        is_cutback: w.isCutback,
        is_taper: w.isTaper,
        is_race_week: w.isRaceWeek,
        is_peak: w.isPeak,
      }),
    );
  }
  out.push('');

  // --- days + sessions + alternatives ---
  out.push('-- days, sessions, alternatives');
  for (const w of plan.weeks) {
    for (const d of w.days) {
      out.push(
        upsert('plan_days', {
          id: dayId(d.date),
          plan_id: pid,
          week_id: weekId(w.weekIndex),
          date: d.date,
          weekday: d.weekday,
          day_index: d.dayIndex,
          days_to_race: d.daysToRace,
          week_number: d.weekNumber,
          phase_label: d.phaseLabel,
          planned_run_km: d.plannedRunKm,
          cumulative_km: d.cumulativeKm,
        }),
      );
      for (const s of d.sessions) {
        out.push(
          upsert('day_sessions', {
            id: sessionId(d.date, s.slot),
            plan_day_id: dayId(d.date),
            slot: s.slot,
            title: s.title,
            category: s.category,
            is_quality: s.isQuality,
            role: s.role,
            prescription_text: s.prescriptionText,
            distance_km: s.distanceKm,
            duration_text: s.durationText,
            duration_min_minutes: s.durationMinMinutes,
            duration_max_minutes: s.durationMaxMinutes,
            pace_text: s.paceText,
            pace_min_s_per_km: s.paceMinSPerKm,
            pace_max_s_per_km: s.paceMaxSPerKm,
            rpe_text: s.rpeText,
            hr_text: s.hrText,
            terrain: s.terrain,
            cue: s.cue,
            fuel: s.fuel,
            shoes: s.shoes,
            completion_planned: s.completionPlanned,
          }),
        );
      }
      for (const a of d.alternatives) {
        out.push(
          upsert('day_alternatives', {
            id: altId(d.date, a.gate),
            plan_day_id: dayId(d.date),
            gate: a.gate,
            prescription: a.prescription,
            distance_km: a.distanceKm,
          }),
        );
      }
    }
  }
  out.push('');

  // --- milestones ---
  out.push('-- milestones');
  for (const ms of plan.milestones) {
    out.push(
      upsert('milestones', {
        id: milestoneId(ms.milestoneIndex),
        plan_id: pid,
        milestone_index: ms.milestoneIndex,
        type: ms.type,
        title: ms.title,
        date: ms.date,
        week_number: ms.weekNumber,
        description: ms.description,
        green_criteria: ms.greenCriteria,
        yellow_criteria: ms.yellowCriteria,
        red_criteria: ms.redCriteria,
      }),
    );
  }
  out.push('');

  // --- checkpoints ---
  out.push('-- checkpoints');
  for (const c of plan.checkpoints) {
    out.push(
      upsert('checkpoints', {
        id: checkpointId(c.checkpointIndex),
        plan_id: pid,
        checkpoint_index: c.checkpointIndex,
        title: c.title,
        after_week: c.afterWeek,
        green_action: c.greenAction,
        yellow_action: c.yellowAction,
        red_action: c.redAction,
      }),
    );
  }
  out.push('');
  out.push('commit;');
  out.push('');
  return out.join('\n');
}

function main(): void {
  const markdown = readFileSync(SOURCE, 'utf8');
  const plan = parsePlan(markdown);
  const sql = generate(plan);
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, sql, 'utf8');
  const days = plan.weeks.reduce((n, w) => n + w.days.length, 0);
  const sessions = plan.weeks.reduce(
    (n, w) => n + w.days.reduce((s, d) => s + d.sessions.length, 0),
    0,
  );
  const alts = plan.weeks.reduce(
    (n, w) => n + w.days.reduce((s, d) => s + d.alternatives.length, 0),
    0,
  );
  console.log(
    `Wrote ${OUT}\n  ${plan.phases.length} phases, ${plan.weeks.length} weeks, ${days} days, ` +
      `${sessions} sessions, ${alts} alternatives, ${plan.milestones.length} milestones, ` +
      `${plan.checkpoints.length} checkpoints`,
  );
}

main();
